package CleanCode.Core.MernisReferance;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 6.0.1.1
//
// Created by Quasar Development 
//
//----------------------------------------------------

import java.util.Date;


public interface VDUDateTimeConverter
{
    Date convertDateTime(String strDate);
    Date convertTime(String strDate);
    Date convertDate(String strDate);
    String convertDuration(String value);
    String getStringFromDateTime(Date value);
    String getStringFromDate(Date value);
    String getStringFromTime(Date value);
    String getStringFromDuration(String value);
}